### ISSUE TITLE
Check LogPub new messages

### ISSUE THREAD

**Issue by schwabe** [fp7-netide/Engine#104]
Commit cc4e58e0c61af93ca8c6caec9bfb2eb65204158a introduced the hooks for LogPub.

I implemented only best guesses for what the method should look like. @KevinPhemius since it is your module please adjust if necessary.

**Comment by KevinPhemius** [comment]
Implemented with commit 6653fa5584cb12e937cf011a895f3835b8c13602

_Old behavior of the LogPub PUB queue:_
- 0 = backend message
- 1 = shimmessage

_New behavior for the LogPub PUB queue:_
- 0 = message _from_ backend
- 1 = message _from_ shim
- 2 = message _to_ backend
- 3 = message _to_ shim

This need to be handled by the Tools.

**Comment by KevinPhemius** [comment]
Also an initial implementation of the topic is in place.
For now all messages are for the topic "*".

**Comment by sergiotamu** [comment]
Hi Kevin,

Have you been able to run the Core properly??? I mean you can run the 
Core, however if you try to make a ping on mininet is not working.
Have you tested the Core to implement the LogPub???

Thanks =)

Best Regards,
Sergio

**Comment by ElisaRojas** [comment]
Hi Kévin,

@ralvarep and me have a similar question as @sergiotamu . Basically, the Engine core is not working right now for us... (we need it for different reasons, for example continue developing the tools and connecting then the tools with the IDE). If you have a specific stable version/deployment, please let us know. Thank you!

**Comment by KevinPhemius** [comment]
Hello,
Sorry if I put you hopes up :(
I only tested the LogPub bundle and wanted to point out the changes in the message format sent to the Tools.
I have the same issues as you running the core.

**Comment by schwabe** [comment]
master should work now. I continuing the new work in a separate branch.

**Comment by sergiotamu** [comment]
Hello @KevinPhemius ,

I have tested the LogPub and it works. I can see the new destinations is '*'. However, I am not sure if it is working properly because in the source field (the field that indicates which module has sent the message) I have "2_ryu_backend_3960" and this tag contains the "2_" so it only should appear in the destination field, shouldn't it?

Best Regards,
Sergio

**Comment by KevinPhemius** [comment]
Hi @sergiotamu,

there is no source **and** destination field anymore.
Now you have a unique _source/destination_ field which contains a _destination_ for 2_ and 3_ messages and a _source_ for 0_ and 1_ messages.
The '*' is the topic of the ZMQ message (as in 'all topic') so if you subscribe to it you will receive all the messages.

Best,
Kévin

**Comment by sergiotamu** [comment]
Hello @KevinPhemius 

I think it would be better if the messages had source and destination fields. In this new implementation you can't know the destination and the source of a message, no?
Besides I think that the '*' topic is not necessary, because with zeromq you can subscribe to all the messages without specifiying a specific topic. If you don't specify anything you are already subscribed to all the messages.

Best,
Sergio

**Comment by KevinPhemius** [comment]
The messages don't have a destination anymore because the topics should take care of that.

_Old behavior_:
Stat_reply to Tool#2 from shim
Source : shim, Destination: Tool#2, Payload: xxx
Problem: the Logger (which is supposed to log **everything**) won't see the message because dest =/= all.

_New behavior_:
Stat_reply to Tool#2 from shim
Topic: Tool#2, Source : shim, Payload: xxx
The Tool#2 is subscribed to his topic, the Logger is subscribed to \* so it will get the message too (and all others). The other tools (and the IDE) are subscribed to their own topics.

That was my understanding of the idea behind using topics. Is it not?

Best,

Kévin

**Comment by sergiotamu** [comment]
Ok, in the first case the "Old behaviour" there is no problem, because the logger can see all the messages without the need of being subscribed to a specifc topic. I attach you the part of the code where the logger retrieves all the messages:

`dst_id, device_id, msg = socket.recv_multipart()`

So, the problem of the "Old behaviour" is solved.

The topics are for the rest of the tools. For example, the profiler only needs to be suscribed to the messages that are sent to it. However, we could use the "destination" field as the "topic" field.
So I would implent it in this way:

Stat_reply to Tool#2 from shim
Destination: Tool#2, Source : shim, Payload: xxx
The Tool#2 is subscribed to his topic (the destination field which is the first field), the Logger can retrieves all the messages without problems.

What do you think about this idea??

Best,
Sergio

**Comment by kjrrp** [comment]
I'm ok with both.
So we can ditch the topics then ? This should be a decision from the WP leader.

Best,

Kévin

**Comment by sergiotamu** [comment]
Actually, the topics would be the "destination" field of the message. So, we will not discard the approach of the topics.

Best Regards,
Sergio

**Comment by kjrrp** [comment]
So the "old" behavior is now back in place.
The source field contains where the message comes from (as shown in https://github.com/fp7-netide/Engine/issues/104#issuecomment-229061777)
The destination is still "*" for now because all messages goes to the LogPub's PUB queue. The routing element will have to indicate the destination so the LogPub can change it if needed.

@schwabe is that something planned in the development?

Best, 

Kévin

**Comment by schwabe** [comment]
@kjrrp I don't know what your are requesting. My understanding of 0MQ topics is that \* will go to all reciever and other topics only to those that are interested. E.g. topics like coretoshim, shimtocore, coretobackend and backendtocore. 

The core just provides the messages to the logpub module with complete information about sender/receiver. Or is there any information that you are missing?

**Comment by sergiotamu** [comment]
Hello @schwabe,

I think that @kjrrp wants to say is that the Core which contains now the necessary logic for routing the messages to the proper destination, should notify the destination field of the message. For instance: Imagine that a tool sends a request statistics message. The message would be composed by three fields:
- The Destination: "Shim" (this is a string)
- The Source: "ProfilerTool" (this is a string)
- The message: The content of the message (bytes)

Then the LogPub receives this message and It only sends the content of the message (the third field) to the Core.

After that, the message arrives to the switches and those switches elaborate a response. The response arrives to the Core **and the Core should notify the destination of that message to the LogPub**, in this case the destination would be "ProfilerTool". With this information the LogPub could modify the destination field of the message and the Tool could subscribe to that destination.

I think that Kevin refers to this when he says if it is something planned in the development...

Best,
Sergio

**Comment by schwabe** [comment]
@sergiotamu The core already does that. When a message is sent to a backend the core calls `OnOutgoingBackendMessage(message, backendId)` on the LogPub. 

For sending requests on its own the LogPub should get the `IOFRoutingManager` service and send the request via    `void sendRequest(m, moduleId, callback);`

I just added the callback function to that function to make it easier for you get to get the results for the message.

**Comment by sergiotamu** [comment]
Hello @KevinPhemius 

I have just pulled the new code from the master branch and I have tested again the core and The LogPug. I don't know why I am receiving in the logger messages with "2_" or "3_", you had removed this and impleted again the old behaviour, hadn't you??. Now I should receive messages with "1_" or "0_" in the source field depending if the message has been sent by the shim or the backend.

Best,
Sergio

**Comment by kjrrp** [comment]
Hello,

you still have to take into account 2_ and 3_ with this behavior.
https://github.com/fp7-netide/Engine/issues/104#issuecomment-229061777

Messages can be **from** the shim (eg. a Packet_IN) or **to** the shim (eg. a Flow_MOD).
In the same way a message can be **to** a backend (eg. a Packet_IN) or **from** a backend (eg. a Flow_MOD).
There can be duplicates (ex. a FlowMod **from** a backend can be the same as a Flow_MOD **to** the shim). But we still need this because for example two backends can send a Flow_MOD (so you will have two _different_ 0_) but the Core can compose them as one Flow_MOD (so there will be one 3_).

Best,

Kévin

**Comment by sergiotamu** [comment]
Hello @KevinPhemius 

Maybe I am missing something. If you have a "destination" field and a "source" field, you don't need the numbers "2_" or "3_" to know if a packet comes from a backend in particular or from the shim. You could have a flow_mod from "0_backend_4586" and another from "0_backend_8347" and then the core would do the composition and will send only one flow_mod to the shim. So, I don't understand why we are using this notation with numbers instead of a "source" field and "destination" field. 
Furthermore, with this notation you are seeing in the logger (for insance) twice the same message, because you will see the flow_mod which source is "0_backend_4586" and the flow_mod whose destination is "3_shim" and it is the same message. So you are receiving duplicates messages in the LogPub and I don't know if this is good for scalability and for the performance tests.

What do you think?? Am I missing something??

Best Regards,
Sergio

**Comment by schwabe** [comment]
@sergiotamu you are missing that some messages are dropped or modified. So most times you see the from shim and to backend messages but for some messages you might not see both messages.

**Comment by sergiotamu** [comment]
@schwabe yes I understand that, but why is the reason for the approach of "numbers" (1_, 2_,  3_) instead of having a destination and a source field??

**Comment by kjrrp** [comment]
@sergiotamu that's why I wanted to drop the whole source/destination thing. It's confusing.

The _source_ field of the message (0_, 1_, 2_, ...) will tell you where the core got it from **and** where it's going to **from the core point of view**.
So 0_ is backend=>core, 1_ is shim=>core, 2_ is core=>backend, 3_ is core=>shim.

The _destination_ field ('*', Profiler, ...) will tell you where the message is supposed to go **from the LogPub point of view**.
So "*" is "this message is for everybody in the PUB queue", "Profiler" is "this message is only for the Profiler"...

Best,

Kévin

**Comment by KevinPhemius** [comment]
Closing if no other comments.
