### ISSUE TITLE
core install error

### ISSUE THREAD

**Issue by chengguozhen** [fp7-netide/Engine#131]
I followed the installation guide:
* Set up a new VM
* Installed Java 8 and Maven 3
* cd Engine/core; mvn clean install -Dgpg.skip=true
* Downloaded karaf 3.0.5
* feature:repo-add mvn:eu.netide.core/core.features/1.1.0-SNAPSHOT/xml/features
*  feature:install core

but feature failed:

netide-core>feature:install core
Error executing command: Can't install feature core/0.0.0: 	
Could not start bundle mvn:org.onosproject/onlab-thirdparty/1.5.1 in feature(s) onos-thirdparty-base-1.5.1: Unresolved constraint in bundle org.onosproject.onlab-thirdparty [1442]: Unable to resolve 1442.0: missing requirement [1442.0] osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))

**Comment by chengguozhen** [comment]
my OS is centOS 6.8~~~~~~

**Comment by ElisaRojas** [comment]
Hi @chengguozhen , 

Could you please check your Maven repository and see if you have the NetIDE artifact there? The default location should be: `~/.m2/repository/eu/netide/...` or something like that. You should find the 1.1.0-SNAPSHOT there if the build was correct. Sometimes erros like `Can't install feature core/0.0.0` are because they can't find the artifact.  

Also, what are your environment variables for Java, Maven, etc.? Could you share? Because it also says `Unable to resolve 1442.0: missing requirement [1442.0] osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))` and it looks like, even if installed, it cannot recognize the Java location.

Finally, you're using Maven 3? You mean 3.3.9 or similar versions? Could you specify the concrete version? 

I'm adding @schwabe to the thread as well, as he's the author of the core.

Thank you!

**Comment by schwabe** [comment]
You need Java 1.8 to run the core.

**Comment by chengguozhen** [comment]
Thanks @ElisaRojas , I checked java environment followed your suggestion, and found that several jdk versions are co-existed, OpenJDK-1.6,1.7 and  JDK 1.8:

[root@localhost java]# rpm -qa | grep jdk
java-1.6.0-openjdk-javadoc-1.6.0.40-1.13.12.6.el6_8.x86_64
java-1.6.0-openjdk-1.6.0.40-1.13.12.6.el6_8.x86_64
java-1.7.0-openjdk-devel-1.7.0.111-2.6.7.2.el6_8.x86_64
java-1.8.0-openjdk-1.8.0.101-3.b13.el6_8.x86_64
java-1.7.0-openjdk-1.7.0.111-2.6.7.2.el6_8.x86_64
java-1.6.0-openjdk-devel-1.6.0.40-1.13.12.6.el6_8.x86_64
java-1.8.0-openjdk-headless-1.8.0.101-3.b13.el6_8.x86_64

 I uninstalled them, and then reinstalled Oracle-JDK 8, and it work. The issue is solved.

**Comment by KevinPhemius** [comment]
> The issue is solved.
