### ISSUE TITLE
Management queue

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#15]
Hi,

I do not understand fully this part of the code from Engine\core\core.connectivity\src\main\java\eu\netide\core\connectivity\ZeroMQBasedConnector.java

``` java
if (poller.pollin(1)) {
                ZMsg message = ZMsg.recvMsg(controlSocket);

                if (message.getFirst().toString().equals(STOP_COMMAND)) {
                    break;
                } else {
                    message.send(socket);
                }
            }
```

I get that if the module gets a message with the STOP_COMMAND, it will break out of the loop and exit.
But what is the purpose of the _else_ statement?

**Edit**: As I understand it, if we receive a STOP_COMMAND on the inproc queue then we stop, else we send the message to the other queue (the one for shim/be messages) because it's not a control message. But I reckon that it's not supposed to happen?

Best,

Kévin

**Comment by TimVinkemeier** [comment]
Hi Kevin,

in your edit you correctly explain what the code does, which is also exactly what it is supposed to do.
Using this additional inproc socket is the recommended pattern for handling multithreading (according to the ZeroMQ Guide).
ZeroMQ sockets are not thread-safe, but since I want to continually be able to receive messages, the receive loop is running on a dedicated thread. Therefore, when I want to send a message through that socket, I have to somehow move it to that thread. It is recommended to use another inproc socket for that, since this solves all threading problems. Additionally, the socket can be used to gracefully shutdown the receive loop. In this case we assume that we either receive a `STOP_COMMAND` or a message to be sent (therefore the else).

So yes, although it looks a bit complicated, it is really supposed to work like that and it is actually an elegant method to handle the threads :smiley: 

Best,
Tim
