### ISSUE TITLE
Information needed by the Garbage Collector from the Core

### ISSUE THREAD

**Issue by amarsico** [fp7-netide/Engine#25]
Dear Tim,

I would like to ask you some help for the Garbage Collector implementation with ZeroMQ protocol. 

The Garbage Collector, in the first use case that we implemented, deletes all the rules from the network devices that the modules deactivated left.
I need the following information from the Core to make it running:
- PacketIn
- Module start/stop
- FlowMod
- OpenFlow Error messages

It also should be able to interact with the network devices (e.g. send flow mods)

I took a look at your core implementation, first of all I saw that there are three different ZeroMQ sockets:
- LogPub (port 5557)
- ZeroMQBasedConnector (port 5555)
- ZeroMQBasedManagementConnector (port 5556)

Which one I should use to retrieve all the informations required? I should create another one like the LogPub?

Otherwise I think that the Garbage Collector can autonomously parse the NetIDE protocol. However it needs all the messages exchanged between `shim` and `backend`.

Moreover we should think, obviously later, how it should cooperate with the composition mechanism.

**Comment by ElisaRojas** [comment]
Hi Antonio,

Initially the LogPub is expected to exchange all these messages you need with the different tools. Kévin prepared a first version of it, which is just a PUB queue from which we will take messages. Andrés is expected to test this with the logger and debugger. Then, after his holidays, Kévin (with the help of Sergio if needed) will start preparing the second part, a SUB queue for the LogPub, so that it can also receive messages from the tools.

So, it is time to start defining what the LogPub should do with that SUB queue. A first approach would be: applying all the actions it receives as they are. For example, if the Garbage Collector sends a FlowMod, the LogPub simply sends that FlowMod to the shim as it is. What do you think? Do you need something else for the GC? Please share it with us, @amarsico . 

Also @KevinPhemius , @sergiotamu , @andres-beato , share your ideas if you had something different in mind. @TimVinkemeier , also tell us in what sense this might affect to the composition module as well.

**Comment by ElisaRojas** [comment]
And I forgot... @TimVinkemeier , also tells us in what sense this might affect to the composition module as well.

**Comment by hkarl** [comment]
Hi,

wouldn’t that also be naturally hosted in Arne’s BigFlowTable?

Best,

HK

On 04.09.2015, at 22:20, Elisa Rojas notifications@github.com wrote:

> Hi Antonio,
> 
> Initially the LogPub is expected to exchange all these messages you need with the different tools. Kévin prepared a first version of it, which is just a PUB queue from which we will take messages. Andrés is expected to test this with the logger and debugger. Then, after his holidays, Kévin (with the help of Sergio if needed) will start preparing the second part, a SUB queue for the LogPub, so that it can also receive messages from the tools.
> 
> So, it is time to start defining what the LogPub should do with that SUB queue. A first approach would be: applying all the actions it receives as they are. For example, if the Garbage Collector sends a FlowMod, the LogPub simply sends that FlowMod to the shim as it is. What do you think? Do you need something else for the GC? Please share it with us, @amarsico .
> 
> Also @KevinPhemius , @sergiotamu , @andres-beato , share your ideas if you had something different in mind.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Prof. Dr. Holger Karl
Computer Networks group - http://wwwcs.upb.de/cs/cn/
Chairman of the board of the
Paderborn Center for Parallel Computing - http://pc2.de/
Universität Paderborn
Tel.: (05251) 60-5375 FAX: (05251)60-5377
Need to talk to me? -  http://tinyurl.com/k2qht4w

---

Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by amarsico** [comment]
Dear @ElisaRojas,
thank you for your clarifications. Yes, in my opinion the SUB queue should send the message directly to the `shim`. Otherwise the tools cannot interact with the network devices.

@hkarl: Yes, the BigFlowTable could simplify the GC implementation. However I think that we should talk with @schwabe because we should understand how to query the BigFlowTable through ZeroMQ approach.

If you have already a solution, please let me now. Otherwise we can discuss about it.

**Comment by TimVinkemeier** [comment]
Hi all,

I think we have to clarify the responsibilities:
The LogPub is meant to pump out all information necessary for the tools, as @ElisaRojas already explained.
For the direction tools->core, we have basically two possibilities:
- Using the management interface
- Extending the LogPub with a SUB queue.

For both I see good arguments and downsides:
- Extending the LogPub and not using the management interface would keep the concerns of managing the core and tooling the network separate. This is desirable, I guess :wink: 
- Extending the LogPub would also (likely) mean introducing a new protocol other than the NetIP Management protocol (which is not yet clearly defined). This is not so desirable... (We could of course use it for the LogPub as well and still keep the concerns separate)
- Using the management interface would prevent the addition of _yet another_ port to the core

Now to the rest of the points:
- I agree that the BigFlowTable should be accessible to the tools, since it is the natural point to keep the "global" knowledge
- FlowMods from the GC will have to be added to the BFT, to keep it up-to-date
- The module start/stop information has to be provided by the backends via a management message. There is no other way for the core to know that.
- Generally, the GC should not have an impact on the composition. When the GC runs, it will delete unused flow rules from the switches and the BFT. The composition mechanism should be made aware of the changes via the BFT, so that it can adapt if necessary. This can be treated similar to a flow timeout, I guess.

Sorry for the long comment, I just wanted to address all of the points.
Please comment :wink:

**Comment by doriguzzi** [comment]
> Generally, the GC should not have an impact on the composition. When the GC runs, it will delete
> unused flow rules from the switches and the BFT. The composition mechanism should be made aware 
> of the changes via the BFT, so that it can adapt if necessary. This can be treated similar to a flow 
> timeout, I guess.```

I'm not sure that have correctly understood this point. It is true that the GC removes the unused rules from the memory of the switches, but it is also true that the GC cleans the rules that have been installed by  modules (composing the network application) that are no longer running (maybe because of an update of the module itself).
In the latter scenario, it is also possible that the rules installed by the module were previously composed with rules generated by other modules. How do we treat them?
I believe that we should foresee a "de-composition" mechanism that the GC can feed with something like: "hey, the rule A must be removed from the composed rule A+B+C".
To this purpose the GC should maintain a database of all the rules generated by the modules and the composed rules that are actually installed on the devices by CaoS (unless CaoS already maintains such a database).
I also think that the GC should be treated like any other application, it should not have the direct access to the devices, but its flow_mods (with the REMOVE operation) should go through the de-composition mechanism of CaoS that finally sends the update to the devices.

What do you think?

**Comment by TimVinkemeier** [comment]
> I believe that we should foresee a "de-composition" mechanism that the GC can feed with something like: "hey, the rule A must be removed from the composed rule A+B+C".
> To this purpose the GC should maintain a database of all the rules generated by the modules and the composed rules that are actually installed on the devices by CaoS (unless CaoS already maintains such a database).
> I also think that the GC should be treated like any other application, it should not have the direct access to the devices, but its flow_mods (with the REMOVE operation) should go through the de-composition mechanism of CaoS that finally sends the update to the devices.

I agree - mostly at least. I think that it would make more sense to keep the knowledge about individual and composed rules inside the BigFlowTable, accessible for every component (since the GC needs to use it, but is not really writing new rules in there). I also think that it is a good idea to send everything through caos, so we can keep track if necessary.
However, de-composition might be hard to do. Maybe it is possible to de-compose a rule A+B+C back to only B+C, but we would have to be sure that that does not introduce any other conflicts. On the other hand, we could fake-timeout all affected rules (meaning those that are composed including A and their individual rules) and force the controller to re-install them (e.g. timeout the rule A+B+C and any rules B+C, A+B, A+C,B,C). This would give us a definitely valid composition. And since I imagine that the GC will not run very often, the impact should be negligible (?!).

**Comment by schwabe** [comment]
Yes. The BigFlowTable is designed to keep track of these flows and also react to changes.

Current working idea is that the bigflow knows every flow that should be installed in the network and also keeps track of the flows that are actually installed in the network.

In the simple approach the flowtable would not modify any flow that is send from an app to the core and pass it through the network. This is the boring mode of operation.

The more interesting approach is to redirect all flowmods to the big flow table. That way the bigflowtable can optimize the rules and do better optimization.

As a simple example (this simple example might even work without the bigflowtable, but more complex situation probably will not work w/o the bigflowtable).

App1 (forwarding app) install rules on Switch A, B, C, D, E, F to forward a packet form Host X on switch A to Host Y on Switch F. The App2 (FW app) install a flow on switch A to drop all packets going from X to Y.  A simple per switch flow mod conflict resolution will detect the conflict on switch A and give App2's rule priority (dropping the rule of App1). On the other switches there is no conflict between App1 and App2, so App2's rules are installed. Of course these rules do no harm but also do nothing useful. My BigFlowTable approach can detect this situation and not install any flow from App1 at all.

**Comment by doriguzzi** [comment]
@schwabe 
Probably it is my fault, but  I've never heard of this BigFlowTable before this chat. What the GC needs is something that (i) keeps track of the rules generated by the single modules composing the network application  and (ii) maintains the association between the these rules and the "composed" ones that have been actually installed on the devices by CaoS. Can BigFlowTable do this?  How BigFlowTable is integrated with the NetIDE architecture? How does it cooperate with CaoS (from your description, it seems to me that they operations can conflict in some cases)?

@TimVinkemeier 

> However, de-composition might be hard to do. Maybe it is possible to de-compose a rule A+B+C 
> back to only B+C, but we would have to be sure that that does not introduce any other conflicts. 

I'm not completely sure on how hard it is. However, it seems to me that it is an interesting problem to investigate. What do you think?

> On the other hand, we could fake-timeout all affected rules (meaning those that are composed 
> including A and their individual rules) and force the controller to re-install them (e.g. timeout the rule 
> A+B+C and any rules B+C, A+B, A+C,B,C). This would give us a definitely valid composition. And 
> since I imagine that the GC will not run very often, the impact should be negligible (?!).

Maybe it is better if we discuss it f2f in Dublin next week...

**Comment by TimVinkemeier** [comment]
@doriguzzi Yes I guess so, it is a quite complex topic that is hard to discuss in text.
I also think that the decomposition would be interesting, however, I will most likely not have the time to look into that :confused: 

Regarding the BigFlowTable, yes, I think that might do similar things at some points. I would also like to discuss that in Dublin, since then I have the opportunity to present what CaOs does and how I think it should integrate...

**Comment by schwabe** [comment]
@doriguzzi I presented the idea in last the last Munich meeting. Kooperation between CaoS and the Bigflowtable are currently still under development. At the moment Tim and I are working on parts that do not conflict with each other. At the moment I am implement the bigflowtable as a module inside the core (like coas or the other modules) becuase I think it will be rather tightly integerated in the core once finished. The design goal is to to have a service that other modules can build upon. One module that could use is the the caos conflict resolution. Another module that I plan on working on next is an optimization module that transform the rules stored in the bigflow into fewer more efficient rules that keep the same semantics.

**Comment by TimVinkemeier** [comment]
@schwabe Not completely sure about the "more efficient" thing, but CaOs can merge rules as part of the conflict resolution (e.g. if two rules have equivalent matches, they can be compressed into one with all actions)...

**Comment by schwabe** [comment]
@TimVinkemeier more efficient in a way that has nothing todo with conflict resolution but an optimization that comes from the fact that the Bigflowtable has a global view and exploit this fact to rewrite rules.

**Comment by TimVinkemeier** [comment]
Okay good :wink: 
There is so much goind on, I can hardly keep track on what is required for me to know as part of the thesis and what are things that are desirable but out of scope, since I am working on so much NetIDE stuff :smiley:
