### ISSUE TITLE
Persistent Datapath IDs

### ISSUE THREAD

**Issue by TimVinkemeier** [fp7-netide/Engine#27]
The shims have to take care of maintaining datapath IDs when relaying messages between the core and network elements.

**Comment by doriguzzi** [comment]
This is already foreseen by the NetIDE intermediate protocol.

**Comment by TimVinkemeier** [comment]
But it is not implemented, I guess? In the shim, I mean...

**Comment by doriguzzi** [comment]
I do not know what shim implementation you are referring to, but onos and ryu shims implement this, otherwise it would have been impossible to make them work with the backends and their applications on top of them. I' m referring to the versions based on sockets available on the master branch on github.
E.g., in ryu-shim:

```
msg_to_send = NetIDEOps.netIDE_encode('NETIDE_OPENFLOW', None, None, self.datapath.id, str(msg.buf))
#Forward the message to all the connected NetIDE clients
for client in self.backend_server.clients:
            client.send(msg_to_send)
```

**Comment by TimVinkemeier** [comment]
Okay great, we were not completely sure about that.
This then only applies to the ODL shim.
