### ISSUE TITLE
Talking to shim/backend

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#48]
Hello,

I would like to implement a simple way to transmit messages to the shim/backend.
I put a new branch called LogPubSub.
(see 430835f)

If I want to transmit the messages from the sub queue "as-is", can I use the bundle core.connectivity (if so how) or do I have to re-implement everything?

Best,

---

Kévin

**Comment by doriguzzi** [comment]
What kind of message do you want to send to shim and backends?  This is something new to me....

**Comment by KevinPhemius** [comment]
I forwarded the discussion to your email.

**Comment by kjrrp** [comment]
Hello,

i added a dependancy to core.connectivity and added the Shim/BackendManager (see  5619ac3)
I cannot do automatic testing during compilation because when the LogPub is being tested, the connector is not available so there is a NullPointerException.

Is it the way to go or am I in the wrong direction?

Best,

**Comment by schwabe** [comment]
@kjrrp I replied directly on the commit.
