### ISSUE TITLE
Malformed NetIDE packets in Ryu backend/shim

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/Engine#55]
I'm seeing this malformed packets at the beginning of the execution of the Ryu backend and shim (it happens both with the Java and the Python core):

![malformed1](https://cloud.githubusercontent.com/assets/2779496/11059663/46e24c1c-879b-11e5-89d8-119f4c48ac0c.png)
![malformed2](https://cloud.githubusercontent.com/assets/2779496/11059665/489b077e-879b-11e5-9711-b92fe5c95f16.png)

No big deal, since they do not seem to be causing any problem (and they don't appear any more once the handshake is done), but just in case you want to know @doriguzzi :)

Maybe is somehow related to v1.2?

**Comment by doriguzzi** [comment]
Who does generate these packets? Backend or Shim?
Are you using the latest version of python stuff (backend,shim,core,netlib)?
Malformed means (AFAIK) that the structure of the header does not correspond to the expected format. This should not happen, as in version 1.2 we have just added some more message TYPES.

**Comment by ElisaRojas** [comment]
@doriguzzi I updated everything, yes (backend, shim, core, netlib).

It happens in all directions, shim->core and back, core->backend and back. I've also notice some NetIDE messages which are not shown as "malformed", but show weird versions and types (versions higher than 2 and types like 80, 85, etc).

After those malformed messages, the first message I see is a type 5 from core to backend and a response with type 4 from backend to core.

After those 5, 4 exchanges, I see the NetIDE_HELLO messages...

And then, the rest as usual (the malformed packets do not show any time after this).

If you need the Wireshark capture or any other detail, please let me know.

**Comment by schwabe** [comment]
@ElisaRojas can you share the pcap file? I would like look into it.

**Comment by ElisaRojas** [comment]
@schwabe Of course, I've sent it to your email (please let me know if you haven't received it).

This behavior is "funny". I mean, it happens for both cores, so I'm starting to be suspicious of the NetIDE dissector itself. I've emailed the capture to @andres-beato as well, so that he can check what is going on.

Let's wait for his opinion, in the meantime this does not look as a big deal (not causing any problems, as I said).

**Comment by schwabe** [comment]
Yeah, it seems the malformed packets are part of the ZMQ handshake.

**Comment by andres-beato** [comment]
Those packets don't seem to be NetIDE protocol msgs, as Roberto said, malformed means that the structure of the header does not correspond to the expected format, and that's what is happening in this case. As you can see in the picture below, these msgs don't have the netide header and they seem an schange between the core and shim/backend. It is possible that the NetIDE dissector believes that they are NetIDE msg because this differentiation is done by the port 5555, so all msgs from the tcp protocol in port 5555 are dissected by the NetIDE protocol.

![image](https://cloud.githubusercontent.com/assets/11061465/11061404/2629a25c-87a7-11e5-8539-6b17af11d598.png)

Any idea about if these messages must belong to the NetIDE protocol, @doriguzzi? Otherwise IMHO, we can ignore them.

**Comment by schwabe** [comment]
that seems to be the ZMQ Hello message. http://rfc.zeromq.org/spec:15

From the tcpdump @ElisaRojas has sent me:
![image](https://cloud.githubusercontent.com/assets/1038539/11062100/63722788-87ac-11e5-8dd5-675840c69cdc.png)

Notice that the ZMTP/2 handshake is split into multiple packets in the one direction and in the other direction the handshake _and_ the first NetIDE packets in one packet. (Which the dissector cannot handle).

**Comment by ElisaRojas** [comment]
Ok, thank you @schwabe , @andres-beato :)
Now that we know what is going on, I think we can close the issue :)
