### ISSUE TITLE
Manual changes in files for installing Engine modules

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/Engine#76]
Some Engine modules (right now, the FL backend and the ONOS shim) require manual modifications of specific files. This is not bad for "humans" (just requires a bit more time to be done, for example in the current FL backend we have to modify 4 files: build.xml, IFloodlightModule, floodlight.sh and Controller.java) and I guess it's more "elegant" than doing it in a fixed way.

The problem with this is for the IDE, because the IDE is based on 'scripts', so "manual" stuff is quite complex sometimes: you need to develop the intelligence to take a file and modify it 'manually' instead of simple replacing. For example, for the old FL backend, we ended up having an extra folder with the files modified in a static way, which the IDE would take to create the VMs...

For this reason, I think it would make sense to have both options: the manually modified files and the instructions. And you choose one of them at your own risk! but at least the IDE is able to directly replace files instead of some more complex behaviour (at least for now... until we have a more stable solution). What do you think?

I'm assigning @peppepetra to this task, but I'm also interested in the opinion of @amarsico , because it happens something similar with the creation of the cell in ONOS, for example.

**Comment by amarsico** [comment]
Hi @ElisaRojas,
in the case of ONOS the cell file is needed in order to deploy correctly the instance in a remote VM. This file contains the BASH variables, such as the IP of the VM, the startup applications, and the cluster configuration. 
In our case we can create a script that dynamically gets the IP of the VM, generates the cell file and puts it in the `ONOS_ROOT/tools/test/cells/ folder.

**Comment by amarsico** [comment]
Hi @ElisaRojas,
in the case of ONOS, the cell file is needed in order to deploy correctly the instance in a remote VM. This file contains the BASH variables, such as the IP of the VM, the startup applications, and the cluster configuration. 

In our case we can create a BASH script that works in this way:
- dynamically gets the IP of the VM
- generates the cell file
- puts it in the `ONOS_ROOT/tools/test/cells/` folder
- executes the command `cell *our_file_name*`

I think that it can be easily deployed, let me know what do you think.

**Comment by ElisaRojas** [comment]
Thank you @amarsico , that would be enough :smile:

**Comment by ElisaRojas** [comment]
@peppepetra I've added the 4 files to be modified in a `manual` folder and already talked about it with @cstritzke . Also added this information in the Readme file.

The only missing one is the ODL's Karaf file (to change the ports when we want to run the Java core as well). Let me know where we should put it. Thanks!
